### ISSUE TITLE
conduit indexer format

### ISSUE THREAD

**Issue by ScalableIntegration** [algorand/conduit#80] opened 2023-05-17 08:29 UTC
Hi! We started to use algorand/conduit with algorand/indexer and found undesirable behavior:
 $ curl 0:8980/v2/blocks/28992333
{"message":"error while looking up block for round '28992333': json decode error [pos 729]: failed to decode address v+gWVeweiq9PYHJc2Wh+C8najmt9AMQQHqsCDEgPKnk= to base 32"}

It seems that happens because conduit writes values in base64 format to the database, whereas indexer wrote and expects this field in base32 format.
Are you aware of this problem? Will next release of conduit fix this?

**Comment by ScalableIntegration** [comment] 2023-05-17 08:32
Besides when stitched to conduit & follower node we lost the ability to request block hash for historical data: GET 0:8080/v2/blocks/28992333/hash.
Is it possible to add this endpoint to the indexer api?

**Comment by tzaffi** [comment] 2023-05-17 19:34
@ScalableIntegration - thanks for alerting us to this issue.

We would like to be able to reproduce your problem so we can debug and fix it. The more information that you provide about the steps you took to get to your problem, the easier our task will be. 

As a starting point, could you provide the following:
* Which versions of conduit and indexer are you using?

You can get this information for conduit using `./conduit -v` and for similarly for indexer.

Other nice to haves would be:

* how did you set up your system?
* what was your conduit config? (**please remove any sensitive data**)
* what command did you use to run conduit?
* any other detailed information you can provide would be great!

**Comment by ScalableIntegration** [comment] 2023-05-18 12:28
@tzaffi 
$ ./conduit --version
Conduit Dev Build (d523bc4)

$ ./algorand-indexer --version
2.15.3 compiled at 2023-02-23T21:18:14+0000 from git hash 3223f6314e56c10764ef1843e536625a6678eaa6 (modified)


$ cat conduit.yml
log-level: INFO
log-file: /var/log/algorand-conduit/algorand-conduit.log
retry-count: 10
retry-delay: "1s"
hide-banner: false
metrics:
  mode: OFF
  addr: ":9999"
  prefix: "conduit"
importer:
  name: algod
  config:
    mode: "follower"
    netaddr: "http://127.0.0.1:8080"
    token: "..."
    catchup-config:
        catchpoint: ""
        admin-token: "..."    
processors:
exporter:
  name: postgresql
  config:
    connection-string: "host=127.0.0.1 ..."
    max-conn: 20
    delete-task:
      interval: -1
      rounds: 2250000

# cat indexer.yml
postgres-connection-string: "host=localhost ..."
pidfile: "/data/indexer_data/algorand-indexer.pid"

# algorand-conduit.service
/bin/conduit --data-dir /data/conduit_data

# algorand-indexer.service
/bin/algorand-indexer daemon --data-dir /data/indexer_data --no-algod


# to reproduce from scratch:
1. use algorand archive node + indexer, and sync to at least first block with block_header->partupdrmv not empty, e.g. 19761974 on mainnet

# select round, header->'partupdrmv' as partupdrmv from block_header where header->>'partupdrmv' != '' order by round asc limit 2;
  round   |                           partupdrmv                           
----------+----------------------------------------------------------------
 19761974 | ["MASCJ7GM54XVOCKKJ73KCWNRVSW43WRDDZZMOSU64R2XPSZMQAHICJWVQ4"]
 19761985 | ["SRHUNXWUCVJQG32SQJJQT2OUINAXECSETZBLLEDAEJKMAWJ5S23AWUW6GY"]

2. stop node & algorand
3. run follower node + indexer (read-only) + conduit from checkpoint, wait until next block_header->partupdrmv not empty, e.g. 19761985 on mainnet
4. ask indexer for that block: curl 0:8980/v2/blocks/19761985

As you see, in our database round 19761985 still have partupdrmv in base32 format. That's because we switched to conduit later. But for the latest blocks, filled with conduit:
# select round, header->'partupdrmv' as partupdrmv from block_header where header->>'partupdrmv' != '' order by round desc limit 2;
  round   |                                            partupdrmv                                            
----------+--------------------------------------------------------------------------------------------------
 29000008 | ["//OHxWUL47ky5v9L2mmS4eCEE1T86nH659Va8H61APg=", "W6wT8DrzJhzoju12pRo0vaFaBtHzdl5BhyaZ5Tfp9aQ="]
 28992333 | ["v+gWVeweiq9PYHJc2Wh+C8najmt9AMQQHqsCDEgPKnk="]

**Comment by winder** [comment] 2023-05-23 17:05
We're continuing to investigate the root cause and come up with a solution.

It is related to decoupling go-algorand from these projects, which has led to this undesirable serialization change. What you've identified for us is that go-algorand is encoding addresses in the "Base32 + Checksum" format, while go-algorand-sdk is encoding them as standard Base64.

```
// old code using go-algorand
type blockHeader struct {
	bookkeeping.BlockHeader
	BranchOverride      crypto.Digest `codec:"prev"`
	FeeSinkOverride     crypto.Digest `codec:"fees"`
	RewardsPoolOverride crypto.Digest `codec:"rwd"`
}

// new code using go-algorand-sdk
type blockHeader struct {
	sdk.BlockHeader
	BranchOverride      sdk.Digest `codec:"prev"`
	FeeSinkOverride     sdk.Digest `codec:"fees"`
	RewardsPoolOverride sdk.Digest `codec:"rwd"`
}
```

**Comment by winder** [comment] 2023-05-30 20:42
This is fixed in the following issues, we plan to have a release this week:
[algorand/indexer#1530](https://github.com/algorand/indexer/issues/1530)
[algorand/indexer#1530](https://github.com/algorand/indexer/issues/1531)

Aside from this, how has Conduit been?

**Closed by winder** 2023-05-30 20:42 UTC
Labels: bug, Team Lamprey
